// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosterPrintRequest.Infrastructure.Persistence;

#nullable disable

namespace PosterPrintRequest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosterPrintRequestDbContext))]
    [Migration("20261006214544_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosterPrintRequest.Domain.ApprovalSheet", b =>
                {
                    b.Property<int>("ApprovalSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalSheetId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosterRequestId")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApprovalSheetId");

                    b.HasIndex("PosterRequestId")
                        .IsUnique();

                    b.ToTable("ApprovalSheets");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.PosterFile", b =>
                {
                    b.Property<int>("PosterFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PosterFileId"));

                    b.Property<string>("DetectedFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Length")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("PosterRequestId")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Width")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("PosterFileId");

                    b.HasIndex("PosterRequestId")
                        .IsUnique();

                    b.ToTable("PosterFiles");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.PosterProcessing", b =>
                {
                    b.Property<int>("PosterProcessingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PosterProcessingId"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOut")
                        .HasColumnType("date");

                    b.Property<string>("ITPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Laminated")
                        .HasColumnType("bit");

                    b.Property<bool>("Notified")
                        .HasColumnType("bit");

                    b.Property<string>("PickedUpBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosterRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("Printed")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("Received")
                        .HasColumnType("date");

                    b.HasKey("PosterProcessingId");

                    b.HasIndex("PosterRequestId")
                        .IsUnique();

                    b.ToTable("PosterProcessings");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.PosterRequest", b =>
                {
                    b.Property<int>("PosterRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PosterRequestId"));

                    b.Property<bool>("ApprovalSheetUploaded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LaminationRequested")
                        .HasColumnType("bit");

                    b.Property<string>("Mentor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PosterRequestId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PosterId")
                        .IsUnique();

                    b.HasIndex("ReasonId");

                    b.ToTable("PosterRequests");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.Reason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresApprovalSheet")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresMentor")
                        .HasColumnType("bit");

                    b.HasKey("ReasonId");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.ApprovalSheet", b =>
                {
                    b.HasOne("PosterPrintRequest.Domain.PosterRequest", "PosterRequest")
                        .WithOne("ApprovalSheet")
                        .HasForeignKey("PosterPrintRequest.Domain.ApprovalSheet", "PosterRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosterRequest");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.PosterFile", b =>
                {
                    b.HasOne("PosterPrintRequest.Domain.PosterRequest", "PosterRequest")
                        .WithOne("PosterFile")
                        .HasForeignKey("PosterPrintRequest.Domain.PosterFile", "PosterRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosterRequest");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.PosterProcessing", b =>
                {
                    b.HasOne("PosterPrintRequest.Domain.PosterRequest", "PosterRequest")
                        .WithOne("PosterProcessing")
                        .HasForeignKey("PosterPrintRequest.Domain.PosterProcessing", "PosterRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosterRequest");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.PosterRequest", b =>
                {
                    b.HasOne("PosterPrintRequest.Domain.Department", "Department")
                        .WithMany("PosterRequests")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PosterPrintRequest.Domain.Reason", "Reason")
                        .WithMany("PosterRequests")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.Department", b =>
                {
                    b.Navigation("PosterRequests");
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.PosterRequest", b =>
                {
                    b.Navigation("ApprovalSheet");

                    b.Navigation("PosterFile")
                        .IsRequired();

                    b.Navigation("PosterProcessing")
                        .IsRequired();
                });

            modelBuilder.Entity("PosterPrintRequest.Domain.Reason", b =>
                {
                    b.Navigation("PosterRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
